---
title: "loading dig.df"
author: "CGDH"
date: "2025-11-22"
output: html_document
---


```{r}
dig.df <- read_csv("DIG.csv", 
                    col_names = TRUE, 
                    col_select = c(ID, TRTMT, AGE, SEX, BMI, KLEVEL, CREAT, DIABP, SYSBP, HYPERTEN, CVD, WHF, DIG, HOSP, HOSPDAYS, DEATH, DEATHDAY),
                    col_types = cols(
    ID = col_integer(),
    TRTMT = col_logical(),
    AGE = col_integer(),
    SEX = col_factor(),
    BMI = col_double(),
    KLEVEL = col_double(),
    CREAT = col_double(),
    DIABP = col_integer(),
    SYSBP = col_integer(),
    HYPERTEN = col_logical(),
    CVD = col_logical(),
    WHF = col_logical(),
    DIG = col_logical(),
    HOSP = col_logical(),
    HOSPDAYS = col_integer(),
    DEATH = col_logical(),
    DEATHDAY = col_integer(),
  ))

```

```{r}
## label the factors described in the codebook: 
dig.df$TRTMT <- factor(dig.df$TRTMT,
                       levels = c("FALSE", "TRUE"),
                       labels = c("Placebo", "Treatment"))
dig.df$SEX <- factor(dig.df$SEX,
                     levels = c(1, 2),
                     labels = c("Male", "Female"))
dig.df$DEATH <- factor(dig.df$DEATH,
                       levels = c("FALSE", "TRUE"),
                       labels = c("Alive", "Death"))

# More factor variables have been labelled here:
dig.df$HYPERTEN <- factor(dig.df$HYPERTEN,
                       levels = c("FALSE", "TRUE"),
                       labels = c("No History of Hypertension", "History of Hypertension"))
dig.df$CVD <- factor(dig.df$CVD,
                       levels = c("FALSE", "TRUE"),
                       labels = c("No Cardiovascular Disease", "Cardiovascular Disease"))
dig.df$WHF <- factor(dig.df$WHF,
                      levels = c("FALSE", "TRUE"),
                      labels = c("No Worsening Heart Failure", "Worsening Heart Failure"))
dig.df$DIG <- factor(dig.df$DIG,
                       levels = c("FALSE", "TRUE"),
                       labels = c("No Digoxin Toxicity", "Digoxin Toxicity"))

dig.df$HOSP <- factor(dig.df$HOSP,
                       levels = c("FALSE", "TRUE"),
                       labels = c("Not Hospitalized", "Hospitalized"))
```